export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const COMPANY_REQUEST = "COMPANY_REQUEST";
export const COMPANY_SUCCESS = "COMPANY_SUCCESS";
export const COMPANY_FAIL = "COMPANY_FAIL";

export const CREATE_COMPANY_REQUEST = "CREATE_COMPANY_REQUEST";
export const CREATE_COMPANY_SUCCESS = "CREATE_COMPANY_SUCCESS";
export const CREATE_COMPANY_FAIL = "REGISTER_USER_FAIL";

export const LOAD_COMPANY_REQUEST = "LOAD_COMPANY_REQUEST";
export const LOAD_COMPANY_SUCCESS = "LOAD_COMPANY_SUCCESS";
export const LOAD_COMPANY_FAIL = "LOAD_COMPANY_FAIL";


