export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const JOB_REQUEST = "JOB_REQUEST";
export const JOB_SUCCESS = "JOB_SUCCESS";
export const JOB_FAIL = "JOB_FAIL";

export const CREATE_JOB_REQUEST = "CREATE_JOB_REQUEST";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_FAIL = "REGISTER_USER_FAIL";

export const LOAD_JOB_REQUEST = "LOAD_JOB_REQUEST";
export const LOAD_JOB_SUCCESS = "LOAD_JOB_SUCCESS";
export const LOAD_JOB_FAIL = "LOAD_JOB_FAIL";


